/**
 * ************************************************************
 * *************** state attribute template  ******************
 * *** state attribute template by HGlab01 & DutchmanNL ***
 * ************************************************************
 * Object definitions can contain these elements to be called by stateSetCreate function, if not set default values are used
 'ID': {                                    // id of state (name) submitted by stateSetCreate function
        name: 'Name of state',				// {default: same as id} Name definition for object
        type: >typeof (value)<,				// {default: typeof (value)} type of value automatically detected
        read: true,							// {default: true} Name defition for object
        write: true,						// {default: false} Name defition for object
        role: 'indicator.info',				// {default: state} Role as defined by https://github.com/ioBroker/ioBroker/blob/main/doc/STATE_ROLES.md
        modify: ''							// {default: ''} see below
    },
 */

/**
 * Defines supported methods for element modify which can be used in stateAttr.js
 * In addition: 'cumstom: YOUR CALCULATION' allows any calculation, where 'value' is the input parameter.
 * Example:
 * modify: 'custom: value + 1' --> add 1 to the json-input
 *
 *  supported methods (as string):
 *  - round(count_digits as {number})  //integer only
 * 	- multiply(factor as {number})
 *  - divide(factor as {number})
 *  - add(number {number})
 *  - substract(number {number})
 *  - upperCase
 *  - lowerCase
 *  - ucFirst
 *
 * Examples for usage of embeded methods:
 * modify: ['multiply(3.6)', 'round(2)'] --> defined as array --> multiplied by 3.6 and then the result is rounded by 2 digits
 * modify: 'upperCase' --> no array needed as there is only one action; this uppercases the string
 *
 */

/**
 * state attribute definitions
 */

const stateAttrb = {
    0: {
        name: `cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    1: {
        name: `2nd cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    2: {
        name: `3rd cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    3: {
        name: `4th cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    4: {
        name: `5th cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    5: {
        name: `6th cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    6: {
        name: `7th cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    7: {
        name: `8th cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    8: {
        name: `9th cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    9: {
        name: `10th cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    10: {
        name: `11th cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    11: {
        name: `12th cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    12: {
        name: `13th cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    13: {
        name: `14th cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    14: {
        name: `15th cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    15: {
        name: `16th cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    16: {
        name: `17th cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    17: {
        name: `18th cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    18: {
        name: `19th cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    19: {
        name: `20th cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    20: {
        name: `21st cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    21: {
        name: `22nd cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    22: {
        name: `23rd cheapest`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    23: {
        name: `most expensive`,
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    'at 00': {
        name: `0 o'clock`,
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 01': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 02': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 03': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 04': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 05': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 06': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 07': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 08': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 09': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 10': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 11': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 12': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 13': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 14': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 15': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 16': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 17': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 18': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 19': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 20': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 21': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 22': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 23': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 24': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 25': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 26': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 27': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 28': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 29': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 30': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 31': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 32': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 33': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 34': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 35': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 36': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 37': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 38': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 39': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 40': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 41': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 42': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 43': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 44': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 45': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 46': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 47': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 48': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 49': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 50': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 51': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 52': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 53': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 54': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 55': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 56': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 57': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 58': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 59': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 60': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 61': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 62': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 63': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 64': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 65': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 66': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 67': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 68': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 69': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 70': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 71': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 72': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 73': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 74': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 75': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 76': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 77': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 78': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 79': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 80': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 81': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 82': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 83': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 84': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 85': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 86': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 87': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 88': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 89': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 90': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 91': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 92': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 93': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 94': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 95': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 96': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 97': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 98': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    'item 99': {
        name: '',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    '00_to_01': {
        name: '00.00 to 01.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '01_to_02': {
        name: '01.00 to 02.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '02_to_03': {
        name: '02.00 to 03.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '03_to_04': {
        name: '03.00 to 04.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '04_to_05': {
        name: '04.00 to 05.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '05_to_06': {
        name: '05.00 to 06.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '06_to_07': {
        name: '06.00 to 07.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '07_to_08': {
        name: '07.00 to 08.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '08_to_09': {
        name: '08.00 to 09.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '09_to_10': {
        name: '09.00 to 10.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '10_to_11': {
        name: '10.00 to 11.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '11_to_12': {
        name: '11.00 to 12.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '12_to_13': {
        name: '12.00 to 13.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '13_to_14': {
        name: '13.00 to 14.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '14_to_15': {
        name: '14.00 to 15.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '15_to_16': {
        name: '15.00 to 16.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '16_to_17': {
        name: '16.00 to 17.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '17_to_18': {
        name: '17.00 to 18.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '18_to_19': {
        name: '18.00 to 19.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '19_to_20': {
        name: '19.00 to 20.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '20_to_21': {
        name: '20.00 to 21.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '21_to_22': {
        name: '21.00 to 22.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '22_to_23': {
        name: '22.00 to 23.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    '23_to_24': {
        name: '23.00 to 24.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    from_00_to_01: {
        name: 'from 00.00 to 01.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_01_to_02: {
        name: 'from 01.00 to 02.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_02_to_03: {
        name: 'from 02.00 to 03.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_03_to_04: {
        name: 'from 03.00 to 04.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_04_to_05: {
        name: 'from 04.00 to 05.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_05_to_06: {
        name: 'from 05.00 to 06.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_06_to_07: {
        name: 'from 06.00 to 07.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_07_to_08: {
        name: 'from 07.00 to 08.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_08_to_09: {
        name: 'from 08.00 to 09.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_09_to_10: {
        name: 'from 09.00 to 10.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_10_to_11: {
        name: 'from 10.00 to 11.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_11_to_12: {
        name: 'from 11.00 to 12.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_12_to_13: {
        name: 'from 12.00 to 13.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_13_to_14: {
        name: 'from 13.00 to 14.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_14_to_15: {
        name: 'from 14.00 to 15.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_15_to_16: {
        name: 'from 15.00 to 16.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_16_to_17: {
        name: 'from 16.00 to 17.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_17_to_18: {
        name: 'from 17.00 to 18.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_18_to_19: {
        name: 'from 18.00 to 19.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_19_to_20: {
        name: 'from 19.00 to 20.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_20_to_21: {
        name: 'from 20.00 to 21.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_21_to_22: {
        name: 'from 21.00 to 22.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_22_to_23: {
        name: 'from 22.00 to 23.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    from_23_to_24: {
        name: 'from 23.00 to 24.00',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    end_timestamp: {
        name: 'End timestamp',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    start_timestamp: {
        name: 'Start timestamp',
        type: 'number',
        read: true,
        write: false,
        role: 'value.time',
    },
    marketprice: {
        name: 'Marketprice',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
    },
    numberOfHours: {
        name: 'Number of Hours',
        type: 'number',
        read: true,
        write: false,
        role: 'info',
    },
    unit: {
        name: 'Unit',
        type: 'string',
        read: true,
        write: false,
        role: 'info',
    },
    online: {
        name: 'online',
        type: 'boolean',
        read: true,
        write: false,
        role: 'indicator',
    },
    'today sorted short': {
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    'tomorrow sorted short': {
        type: 'string',
        read: true,
        write: false,
        role: 'json',
    },
    average: {
        name: 'average price',
        type: 'number',
        read: true,
        write: false,
        role: 'value',
        unit: '€ct/kWh',
    },
    AuctionDay: {
        name: 'Auction Day',
        type: 'string',
        read: true,
        write: false,
        role: 'info',
    },
    BuyVolume: {
        name: 'Buy Volume',
        type: 'number',
        read: true,
        write: false,
        role: 'info',
        modify: 'round(1)',
    },
    Price: {
        name: 'Price',
        type: 'number',
        read: true,
        write: false,
        role: 'info',
        modify: 'round(2)',
    },
    Product: {
        name: 'Product',
        type: 'string',
        read: true,
        write: false,
        role: 'info',
    },
    ProductText: {
        name: 'Product Text',
        type: 'string',
        read: true,
        write: false,
        role: 'info',
    },
    SellVolume: {
        name: 'Sell Volume',
        type: 'number',
        read: true,
        write: false,
        role: 'info',
        modify: 'round(1)',
    },
    Source: {
        name: 'Source',
        type: 'string',
        read: true,
        write: false,
        role: 'info',
    },
    TotalVol: {
        name: 'Total Volume',
        type: 'number',
        read: true,
        write: false,
        role: 'info',
        modify: 'round(1)',
    },
    jsonChart: {
        name: 'JSON Chart',
        type: 'json',
        read: true,
        write: false,
        role: 'json',
    },
    date: {
        name: 'belongs to',
        type: 'number',
        read: true,
        write: false,
        role: 'date',
    },
};

module.exports = stateAttrb;
